language: node_js
node_js: [node, lts/*]
cache:
  npm: true
script:
  - curl https://gist.githubusercontent.com/Jaid/284917bd3e938add97b699a18b957d8c/raw/ciNode.bash | bash
jobs:
  include:
    - stage: Deploy
      if: tag =~ /^v/
      before_deploy:
        - curl https://gist.githubusercontent.com/Jaid/284917bd3e938add97b699a18b957d8c/raw/ciNodeRelease.bash | bash
      deploy:
        - provider: pages
          local_dir: page
          fqdn: $PKG_NAME.jaid.codes
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            condition: env(DEPLOY_PAGE) IS present
        - provider: releases
          file_glob: true
          file: dist/github/*
          skip_cleanup: true
          api_key: $GITHUB_TOKEN
          on:
            condition: env(DEPLOY_RELEASES) IS present
        - provider: script
          script: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish dist/package/production
          skip_cleanup: true
          on:
            condition: env(DEPLOY_NPM) IS present
